spring.application.name=sandeliukas
spring.datasource.url=jdbc:mariadb://stud.if.ktu.lt:20001/armarl?sslMode=disable
spring.datasource.username=armarl
spring.datasource.password=ahn0ookaThoedoon
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.open-in-view=true
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

spring.thymeleaf.cache=false
server.port=8081